version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: shareit-db
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      TZ: Europe/Moscow
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
